#!/usr/bin/env bash
PROJECT_DIR=/home/julian/Vagrant/Angular/Files
DEFUALT_NAME=angular
PROJECT_NAME=${1-$DEFUALT_NAME}
cd $PROJECT_DIR

tmux has-session -t $PROJECT_NAME 2>/dev/null

if [ "$?" -eq 1 ] ; then
    # Create New Session
    tmux new-session -d -s "$PROJECT_NAME"

    # Pane 2 is the Frontend
    tmux split-window -h -c $PROJECT_DIR
    tmux resize-pane -t 2 -x 60
    tmux send-keys -t 2 'vagrant ssh' Enter C-l

    # Path 3 is Backend
    tmux split-window -t 1 -v -c $PROJECT_DIR

    # Frontend server
    tmux send-keys -t 3 'vagrant ssh' Enter C-l

    # Focus on pane 1
    tmux select-pane -t 1

    # Rename the Window
    tmux rename-window "$PROJECT_NAME dashboard"
fi

tmux -2 attach-session -d -t "$PROJECT_NAME"


