#!/usr/bin/env bash
PROJECT_DIR=/home/julian/CIT-Blossom/cit-blossom
DEFUALT_NAME=blossom
PROJECT_NAME=${1-$DEFUALT_NAME}
cd $PROJECT_DIR

tmux has-session -t $PROJECT_NAME 2>/dev/null

if [ "$?" -eq 1 ] ; then
    # Create New Session
    tmux new-session -d -s "$PROJECT_NAME"

    # Pane 2 is the GulpJS
    tmux split-window -h -c $PROJECT_DIR/_app/frontend
    tmux resize-pane -t 2 -x 60

    # Path 3 is Django
    tmux split-window -t 1 -v -c $PROJECT_DIR/_app

    # Setup virtualenv, gulp and server
    tmux send-keys -t 2 'webpack --watch --verbose --debug' Enter
    tmux send-keys -t 1 'vf activate ansibleEnv' Enter C-l
    tmux send-keys -t 3 'vagrant ssh app-box' Enter C-l

    # Focus on pane 1
    tmux select-pane -t 1

    # Rename the Window
    tmux rename-window "$PROJECT_NAME dashboard"
fi

tmux -2 attach-session -d -t "$PROJECT_NAME"
